// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJDPFwFBlOyZW79dXC-s7Mjg5sLll0Jo',
    appId: '1:245551583852:web:21291bbaa1fd02731efe49',
    messagingSenderId: '245551583852',
    projectId: 'm335-6ad7d',
    authDomain: 'm335-6ad7d.firebaseapp.com',
    storageBucket: 'm335-6ad7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiz5z-KGrhU4N23cu7ehuAXBQgf8mc0Qw',
    appId: '1:245551583852:android:3d07b7794a68ccaf1efe49',
    messagingSenderId: '245551583852',
    projectId: 'm335-6ad7d',
    storageBucket: 'm335-6ad7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDakDREKtKi-9W05-c9XQCVQN-Ix9FuPhY',
    appId: '1:245551583852:ios:8c317c84fb32305f1efe49',
    messagingSenderId: '245551583852',
    projectId: 'm335-6ad7d',
    storageBucket: 'm335-6ad7d.appspot.com',
    iosClientId: '245551583852-j2icrlpoff7o66ehafjufjo6javmnitf.apps.googleusercontent.com',
    iosBundleId: 'com.example.m335',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDakDREKtKi-9W05-c9XQCVQN-Ix9FuPhY',
    appId: '1:245551583852:ios:8c317c84fb32305f1efe49',
    messagingSenderId: '245551583852',
    projectId: 'm335-6ad7d',
    storageBucket: 'm335-6ad7d.appspot.com',
    iosClientId: '245551583852-j2icrlpoff7o66ehafjufjo6javmnitf.apps.googleusercontent.com',
    iosBundleId: 'com.example.m335',
  );
}
